Repository AY2425S2-CS2103T-T16-2/tp, pull requests merged in 2025-03, with the labels that each got.

#20 Add Hai Hui to AboutUs.md
  docs/AboutUs.md
  docs/team/iuhiah.md
Labels: type.Task

#28 Add Michael to AboutUs.md
  docs/AboutUs.md
Labels: type.Task

#37 Fix Michael's AboutUs
  docs/AboutUs.md
  docs/images/michael.png
  docs/images/reshiro.png
Labels: type.Task

#64 Add Whitespace Parsing
  src/main/java/seedu/innsync/commons/util/StringUtil.java
  src/main/java/seedu/innsync/logic/parser/ParserUtil.java
  src/test/java/seedu/innsync/logic/parser/ParserUtilTest.java
Labels: type.Task

#61 Update Phone Validation
  .gitignore
  docs/DeveloperGuide.md
  src/main/java/seedu/innsync/model/person/Phone.java
  src/main/java/seedu/innsync/model/util/CountryCodeUtil.java
  src/main/java/seedu/innsync/model/util/SampleDataUtil.java
  src/main/resources/countrycodes.txt
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/innsync/logic/commands/CommandTestUtil.java
  src/test/java/seedu/innsync/logic/parser/ParserUtilTest.java
  src/test/java/seedu/innsync/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/innsync/model/person/PhoneTest.java
  src/test/java/seedu/innsync/testutil/PersonBuilder.java
  src/test/java/seedu/innsync/testutil/TypicalPersons.java
  src/test/resources/countrycodes.txt
Labels: type.Task, priority.High

#66 Fix datetimeparser in booking tag
  src/main/java/seedu/innsync/model/tag/BookingTag.java
Labels: priority.High

#85 Fix Bugs for Star Command
  src/main/java/seedu/innsync/logic/LogicManager.java
  src/main/java/seedu/innsync/logic/commands/BookingTagCommand.java
  src/main/java/seedu/innsync/logic/commands/DeleteCommand.java
  src/main/java/seedu/innsync/logic/commands/EditCommand.java
  src/main/java/seedu/innsync/logic/commands/FindCommand.java
  src/main/java/seedu/innsync/logic/commands/StarCommand.java
  src/main/java/seedu/innsync/model/Model.java
  src/main/java/seedu/innsync/model/ModelManager.java
  src/main/java/seedu/innsync/model/person/Name.java
  src/test/java/seedu/innsync/logic/commands/AddCommandTest.java
  src/test/java/seedu/innsync/logic/commands/CommandTestUtil.java
  src/test/java/seedu/innsync/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/innsync/logic/commands/EditCommandTest.java
  src/test/java/seedu/innsync/logic/commands/FindCommandTest.java
  src/test/java/seedu/innsync/logic/commands/StarCommandTest.java
  src/test/java/seedu/innsync/model/ModelManagerTest.java
  src/test/java/seedu/innsync/testutil/TestUtil.java
Labels: type.Bug

#86 Implement unstar Command
  src/main/java/seedu/innsync/logic/commands/UnstarCommand.java
  src/main/java/seedu/innsync/logic/parser/AddressBookParser.java
  src/main/java/seedu/innsync/logic/parser/UnstarCommandParser.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Task

#87 Implement liststar Command
  src/main/java/seedu/innsync/logic/commands/ListStarCommand.java
  src/main/java/seedu/innsync/logic/parser/AddressBookParser.java
  src/main/java/seedu/innsync/model/Model.java
Labels: type.Task

#106 Fix grammar and style issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/resources/view/Extensions.css
Labels: type.Task, severity.VeryLow

#99 Add Tests for the unstar Command
  src/test/java/seedu/innsync/logic/commands/FindCommandTest.java
  src/test/java/seedu/innsync/logic/commands/UnstarCommandTest.java
Labels: type.Task

#125 Add incomplete untag command
  src/main/java/seedu/innsync/logic/commands/UntagCommand.java
  src/main/java/seedu/innsync/logic/parser/AddressBookParser.java
  src/main/java/seedu/innsync/logic/parser/UntagCommandParser.java
Labels: priority.High

#121 Change GUI layout and colors
  src/main/java/seedu/innsync/ui/MainWindow.java
  src/main/java/seedu/innsync/ui/PersonDetailPanel.java
  src/main/java/seedu/innsync/ui/PersonListPanel.java
  src/main/resources/view/Extensions.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonDetailPanel.fxml
Labels: type.Task

#128 Fix argument passing in untag command parser
  src/main/java/seedu/innsync/logic/parser/UntagCommandParser.java
Labels: type.Bug, priority.High

#143 Add tests for liststar
  src/test/java/seedu/innsync/logic/commands/ListStarCommandTest.java
Labels: type.Task

#131 Update parser functionality and fix bugs
  src/main/java/seedu/innsync/logic/commands/UntagCommand.java
  src/main/java/seedu/innsync/logic/parser/UntagCommandParser.java
Labels: type.Bug, priority.High

#144 Update User Guide for Find Command
  docs/UserGuide.md
Labels: priority.High
