Repository AY2425S2-CS2103T-T16-2/tp, pull requests merged in 2025-04, with the labels that each got.

#205 Add deletereq command
  src/main/java/seedu/innsync/logic/commands/DeleteRequestCommand.java
  src/main/java/seedu/innsync/logic/parser/AddressBookParser.java
  src/main/java/seedu/innsync/logic/parser/DeleteRequestCommandParser.java
  src/test/java/seedu/innsync/logic/commands/DeleteRequestCommandTest.java
  src/test/java/seedu/innsync/logic/parser/DeleteRequestCommandParserTest.java
Labels: type.Task

#229 Add documentation for request-related commands in the UG
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
Labels: type.Task

#230 Update find command, implement imput validation with custom error messages for Memo, Address and Tag
  docs/UserGuide.md
  src/main/java/seedu/innsync/logic/commands/FindCommand.java
  src/main/java/seedu/innsync/logic/parser/FindCommandParser.java
  src/main/java/seedu/innsync/logic/parser/MemoCommandParser.java
  src/main/java/seedu/innsync/logic/parser/ParserUtil.java
  src/main/java/seedu/innsync/model/person/Address.java
  src/main/java/seedu/innsync/model/person/Memo.java
  src/main/java/seedu/innsync/model/person/Name.java
  src/main/java/seedu/innsync/model/request/Request.java
  src/main/java/seedu/innsync/model/tag/Tag.java
  src/main/java/seedu/innsync/storage/JsonAdaptedPerson.java
  src/test/java/seedu/innsync/logic/commands/CommandTestUtil.java
  src/test/java/seedu/innsync/logic/commands/FindCommandTest.java
  src/test/java/seedu/innsync/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/innsync/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/innsync/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/innsync/logic/parser/ParserUtilTest.java
  src/test/java/seedu/innsync/model/person/AddressTest.java
  src/test/java/seedu/innsync/storage/JsonAdaptedPersonTest.java
Labels: alpha-bug

#232 Standardise Error Messages
  src/main/java/seedu/innsync/logic/Emoticons.java
  src/main/java/seedu/innsync/logic/Messages.java
  src/main/java/seedu/innsync/logic/commands/AddCommand.java
  src/main/java/seedu/innsync/logic/commands/CancelConfirmCommand.java
  src/main/java/seedu/innsync/logic/commands/ClearCommand.java
  src/main/java/seedu/innsync/logic/commands/ConfirmCommand.java
  src/main/java/seedu/innsync/logic/commands/DeleteCommand.java
  src/main/java/seedu/innsync/logic/commands/DeleteRequestCommand.java
  src/main/java/seedu/innsync/logic/commands/EditCommand.java
  src/main/java/seedu/innsync/logic/commands/FindCommand.java
  src/main/java/seedu/innsync/logic/commands/HelpCommand.java
  src/main/java/seedu/innsync/logic/commands/ListCommand.java
  src/main/java/seedu/innsync/logic/commands/ListStarCommand.java
  src/main/java/seedu/innsync/logic/commands/MarkRequestCommand.java
  src/main/java/seedu/innsync/logic/commands/MemoCommand.java
  src/main/java/seedu/innsync/logic/commands/RequestCommand.java
  src/main/java/seedu/innsync/logic/commands/StarCommand.java
  src/main/java/seedu/innsync/logic/commands/TagCommand.java
  src/main/java/seedu/innsync/logic/commands/UndoCommand.java
  src/main/java/seedu/innsync/logic/commands/UnmarkRequestCommand.java
  src/main/java/seedu/innsync/logic/commands/UnstarCommand.java
  src/main/java/seedu/innsync/logic/commands/UntagCommand.java
  src/main/java/seedu/innsync/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/innsync/logic/parser/DeleteRequestCommandParser.java
  src/main/java/seedu/innsync/logic/parser/EditCommandParser.java
  src/main/java/seedu/innsync/logic/parser/FindCommandParser.java
  src/main/java/seedu/innsync/logic/parser/MarkRequestCommandParser.java
  src/main/java/seedu/innsync/logic/parser/MemoCommandParser.java
  src/main/java/seedu/innsync/logic/parser/RequestCommandParser.java
  src/main/java/seedu/innsync/logic/parser/StarCommandParser.java
  src/main/java/seedu/innsync/logic/parser/TagCommandParser.java
  src/main/java/seedu/innsync/logic/parser/UnmarkRequestCommandParser.java
  src/main/java/seedu/innsync/logic/parser/UnstarCommandParser.java
  src/main/java/seedu/innsync/logic/parser/UntagCommandParser.java
  src/test/java/seedu/innsync/logic/LogicManagerTest.java
  src/test/java/seedu/innsync/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/innsync/logic/commands/DeleteRequestCommandTest.java
  src/test/java/seedu/innsync/logic/commands/EditCommandTest.java
  src/test/java/seedu/innsync/logic/commands/MarkRequestCommandTest.java
  src/test/java/seedu/innsync/logic/commands/MemoCommandTest.java
  src/test/java/seedu/innsync/logic/commands/RequestCommandTest.java
  src/test/java/seedu/innsync/logic/commands/StarCommandTest.java
  src/test/java/seedu/innsync/logic/commands/TagCommandTest.java
  src/test/java/seedu/innsync/logic/commands/UnmarkRequestCommandTest.java
  src/test/java/seedu/innsync/logic/commands/UnstarCommandTest.java
  src/test/java/seedu/innsync/logic/commands/UntagCommandTest.java
  src/test/java/seedu/innsync/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/innsync/logic/parser/DeleteRequestCommandParserTest.java
  src/test/java/seedu/innsync/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/innsync/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/innsync/logic/parser/StarCommandParserTest.java
  src/test/java/seedu/innsync/logic/parser/UnstarCommandParserTest.java
  src/test/java/seedu/innsync/logic/parser/UntagCommandParserTest.java
Labels: alpha-bug

#245 Remove listreq from the user guide
  docs/UserGuide.md
Labels: type.Task

#333 Fix typos in the User Guide and Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task

#341 Add Text Wrapping for Memo UI
  src/main/java/seedu/innsync/ui/PersonDetailPanel.java
Labels: type.FunctionalityBug, severity.VeryLow

#342 Add instructions for manual testing to DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.DocumentationBug

#343 Update duplicate check
  src/main/java/seedu/innsync/logic/Messages.java
  src/main/java/seedu/innsync/logic/parser/FindCommandParser.java
  src/main/java/seedu/innsync/model/person/Person.java
  src/main/java/seedu/innsync/model/person/UniquePersonList.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/seedu/innsync/logic/commands/EditCommandTest.java
  src/test/java/seedu/innsync/model/person/PersonTest.java
Labels: priority.High

#354 UG: Update Phone Validation and add command usage for prefix
  docs/UserGuide.md
Labels: type.DocumentationBug

#359 Update DG together with add and edit parameter message
  docs/DeveloperGuide.md
  src/main/java/seedu/innsync/logic/commands/AddCommand.java
  src/main/java/seedu/innsync/logic/commands/EditCommand.java
Labels: type.DocumentationBug

#363 Add error handling for duplicate tags
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/innsync/logic/parser/ParserUtil.java
Labels: type.Task, alpha-bug

#365 Update DeveloperGuide.md to include Planned Enhancements and Effort
  docs/DeveloperGuide.md
Labels: type.DocumentationBug, priority.Medium, severity.Medium

#374 DG: Add Undo Implementation
  docs/DeveloperGuide.md
  docs/diagrams/undo/InitialState.puml
  docs/diagrams/undo/UndoSequenceDiagram.puml
Labels: type.DocumentationBug

#377 Fix error messages for request-related commands
  src/main/java/seedu/innsync/logic/commands/DeleteRequestCommand.java
  src/main/java/seedu/innsync/logic/commands/MarkRequestCommand.java
  src/main/java/seedu/innsync/logic/commands/UnmarkRequestCommand.java
  src/main/java/seedu/innsync/logic/parser/DeleteRequestCommandParser.java
  src/main/java/seedu/innsync/logic/parser/MarkRequestCommandParser.java
  src/main/java/seedu/innsync/logic/parser/UnmarkRequestCommandParser.java
  src/test/java/seedu/innsync/logic/parser/DeleteRequestCommandParserTest.java
  src/test/java/seedu/innsync/logic/parser/MarkRequestCommandParserTest.java
  src/test/java/seedu/innsync/logic/parser/UnmarkRequestCommandParserTest.java
Labels: alpha-bug

#380 Fix UG headers and links
  docs/UserGuide.md
Labels: alpha-bug

#383 Update mark unmark manual testing instructions
  docs/DeveloperGuide.md
Labels: type.DocumentationBug
